INSERT INTO paises (nome_pais) VALUES
('Afeganistão'),
('África do Sul'),
('Albânia'),
('Alemanha'),
('Andorra'),
('Angola'),
('Antígua e Barbuda'),
('Arábia Saudita'),
('Argélia'),
('Argentina'),
('Armênia'),
('Austrália'),
('Áustria'),
('Azerbaijão'),
('Bahamas'),
('Bangladesh'),
('Barbados'),
('Bahrein'),
('Belarus'),
('Bélgica'),
('Belize'),
('Benin'),
('Butão'),
('Bolívia'),
('Bósnia e Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunei'),
('Bulgária'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Camarões'),
('Camboja'),
('Canadá'),
('Catar'),
('Cazaquistão'),
('Chade'),
('Chile'),
('China'),
('Chipre'),
('Colômbia'),
('Comores'),
('Congo'),
('Coreia do Norte'),
('Coreia do Sul'),
('Costa do Marfim'),
('Costa Rica'),
('Croácia'),
('Cuba'),
('Dinamarca'),
('Djibouti'),
('Dominica'),
('Egito'),
('El Salvador'),
('Emirados Árabes Unidos'),
('Equador'),
('Eritreia'),
('Eslováquia'),
('Eslovênia'),
('Espanha'),
('Estados Unidos'),
('Estônia'),
('Etiópia'),
('Fiji'),
('Filipinas'),
('Finlândia'),
('França'),
('Gabão'),
('Gâmbia'),
('Gana'),
('Geórgia'),
('Granada'),
('Grécia'),
('Guatemala'),
('Guiana'),
('Guiné'),
('Guiné-Bissau'),
('Guiné Equatorial'),
('Haiti'),
('Honduras'),
('Hungria'),
('Iémen'),
('Ilhas Marshall'),
('Índia'),
('Indonésia'),
('Irã'),
('Iraque'),
('Irlanda'),
('Islândia'),
('Israel'),
('Itália'),
('Jamaica'),
('Japão'),
('Jordânia'),
('Kiribati'),
('Kosovo'),
('Kuwait'),
('Laos'),
('Lesoto'),
('Letônia'),
('Líbano'),
('Libéria'),
('Líbia'),
('Liechtenstein'),
('Lituânia'),
('Luxemburgo'),
('Macedônia do Norte'),
('Madagascar'),
('Malásia'),
('Malaui'),
('Maldivas'),
('Mali'),
('Malta'),
('Marrocos'),
('Maurícia'),
('Mauritânia'),
('México'),
('Mianmar'),
('Micronésia'),
('Moçambique'),
('Moldávia'),
('Mônaco'),
('Mongólia'),
('Montenegro'),
('Namíbia'),
('Nauru'),
('Nepal'),
('Nicarágua'),
('Níger'),
('Nigéria'),
('Noruega'),
('Nova Zelândia'),
('Omã'),
('Países Baixos'),
('Palau'),
('Panamá'),
('Papua Nova Guiné'),
('Paquistão'),
('Paraguai'),
('Peru'),
('Polônia'),
('Portugal'),
('Quênia'),
('Quirguistão'),
('Reino Unido'),
('República Centro-Africana'),
('República Democrática do Congo'),
('República Dominicana'),
('República Tcheca'),
('Romênia'),
('Ruanda'),
('Rússia'),
('Samoa'),
('San Marino'),
('Santa Lúcia'),
('São Cristóvão e Nevis'),
('São Tomé e Príncipe'),
('São Vicente e Granadinas'),
('Seicheles'),
('Senegal'),
('Serra Leoa'),
('Sérvia'),
('Singapura'),
('Síria'),
('Somália'),
('Sri Lanka'),
('Suazilândia'),
('Sudão'),
('Sudão do Sul'),
('Suécia'),
('Suíça'),
('Suriname'),
('Tailândia'),
('Taiwan'),
('Tajiquistão'),
('Tanzânia'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trindade e Tobago'),
('Tunísia'),
('Turcomenistão'),
('Turquia'),
('Tuvalu'),
('Ucrânia'),
('Uganda'),
('Uruguai'),
('Uzbequistão'),
('Vanuatu'),
('Vaticano'),
('Venezuela'),
('Vietnã'),
('Zâmbia'),
('Zimbábue');

INSERT INTO status(nome_status)
VALUES
  ('Lido'),
  ('Lendo'),
  ('Lista de desejos');

INSERT INTO editora.autores (nome_autor,data_nascimento_autor,genero_autor,pais_autor) 
VALUES
	 ('Affonso Solano','1981-11-13','M',27),
	 ('Agatha Christie','1890-09-15','F',146),
	 ('C.S Lewis','1898-11-29','M',146),
	 ('Josh Malerman','1975-07-24','M',62),
	 ('F. Scott Fitzgerald','1896-09-24','M',62),
	 ('Michael Crichton','1942-10-23','M',62),
	 ('Eduardo Spohr','1976-06-05','M',27),
	 ('Michael Dante DiMartino','1974-07-18','M',62),
	 ('Graziela Gonçalves','1971-01-01','F',27),
	 ('Matt Haig','1975-07-03','M',146);


INSERT INTO editora.generos (nome_genero) 
VALUES
	 ('Ação e Aventura'),
	 ('Suspense'),
	 ('Conto'),
	 ('Ficção Científica'),
	 ('Ficção Histórica'),
	 ('Mistério'),
	 ('Fantasia'),
	 ('Comédia'),
	 ('Biografia');


INSERT INTO editora.editoras (nome_editora) 
VALUES
	 ('LeYa'),
	 ('HarperCollins'),
	 ('Intrínseca'),
	 ('Editora Aleph'),
	 ('Talentos da Literatura Brasileira'),
	 ('Crowell-Collier Publishing Company'),
	 ('Verus'),
	 ('Planeta'),
	 ('Paralela'),
	 ('Bertrand Brasil');


INSERT INTO editora.clientes (nome_cliente,email_cliente,senha_cliente,genero_cliente,pais_cliente,data_nascimento_cliente,adm) 
VALUES
	 ('Pedro Fernando','pedrofernandofb@gmail.com','dicria','M',27,'2004-04-28',NULL),
	 ('Gabriel Barbosa','gabi@gol.fla','231119','M',27,'1996-08-30',NULL),
	 ('Admin','admin','admin','a',1,'0001-01-01',true);


INSERT INTO editora.livros (nome_livro,id_autor_livro,id_editora_livro,data_de_lancamento_livro,id_genero_livro,id_status_livro,ano_lido_livro,nota_livro,resenha_livro,id_cliente_livro) 
VALUES
	 ('O Curioso Caso de Benjamin Button',5,6,'1922-05-27',3,1,2024,6.0,NULL,2),
	 ('O Espadachim de Carvão e a voz do Guardião Cego',1,1,'2021-10-20',1,1,2024,9.0,NULL,2),
	 ('Morte no Nilo',2,2,'1937-11-01',6,1,2024,10.0,NULL,2),
	 ('O Leão, a Feiticeira e o Guarda-Roupa',3,2,'1950-10-16',7,1,2024,7.0,NULL,2),
	 ('A Biblioteca da Meia Noite',10,10,'2020-08-13',4,2,NULL,NULL,NULL,3),
	 ('A ascensão de Kyoshi: O passado da poderosa Avatar do Reino da Terra',8,8,'2019-07-16',1,1,2025,8.0,NULL,2),
	 ('Jurassick Park',6,4,'1990-11-20',4,3,2024,NULL,NULL,2),
	 ('Caixa de Pássaros',4,3,'2015-01-21',2,1,2024,9.0,NULL,2),
	 ('O Santo Guerreiro: Roma Invicta',7,7,'2020-12-07',5,1,2025,6.5,'O livro tem um ritmo estranho. Bom começo e fim porém com uma barriga enorme no meio. A história é bem interessante e possui bons personagens, mas a forma como o autor conduz a história não fica muito legal. A pegada da história, como jornada do herói, com uma pegada que lembra animes shonnen, mas o livro tem uma pegada e um linguajar muito formal e histórico, mas às vezes fica fantasioso e heróico; de forma que nem fica um livro infanto-juvenil nem adulto. No geral fica uma boa experiência de leitura, mas com um gosto amargo de um grande potencial desperdiçado ',2),
	 ('O Espadachim de Carvão',1,1,'2013-01-01',1,1,2024,9.5,NULL,2);
	 ('O Espadachim de Carvão e as pontes de Puzur',1,1,'2015-09-10',1,1,2024,9.0,NULL,2),
	 ('Se não eu, quem vai fazer você feliz?: Minha história de amor com Chorão',9,9,'2018-09-10',9,1,2025,9.0,'Ótimo livro! Boa escrita, em capítulos agéis e interessantes. Por ser ser uma auto-biografia de uma não autora, o livro acaba tendo uma informalidade que aproxima o leitor, tendo em vista que apesar de informal a escrita ainda é muito bem feita. Um livro que mostra que não existe melhor roteirista do que a vida. Uma história bonita de romance, superação e ainda assim drama e tragédia. Com bastidores da relação, da band - desde a origem - história que deram origem a música e muitos pontos positivos fazem o leitor se apaixonar ainda mais pelo Charlie Brown e a história do Alê com a Grazi',2);

  
  
